name: creartify
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  dio: ^5.7.0
  # UI
  flutter_staggered_grid_view: ^0.7.0
  zoom_tap_animation: ^1.1.0
  loading_animation_widget: ^1.3.0
  full_screen_image: ^2.0.0
  gradient_icon: ^2.0.9
  # Downloader
  flutter_downloader: ^1.11.8
  permission_handler: ^11.3.1
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: TTNorms
      fonts:
        - asset: assets/fonts/TTNorms-Medium.otf
